apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
  labels:
    app: discovery-server
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30003  # Choose a port within the NodePort range (30000-32767)
