spring:
  application:
    name: gateway-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com:
      south: DEBUG
    org:
      springframework:
        WARN: WARN
        kafka: INFO
  file:
    name: /dev/stdout
    max-history: 7
    max-size: 10MB
